### ISSUE TITLE
Replace cs_instance_facts as it is deprecated

### ISSUE THREAD

**Issue by nop33** [arillso/ansible.exoscale#3]
```
[DEPRECATION WARNING]: cs_instance_facts is kept for backwards compatibility but usage is discouraged.
 The module documentation details page may explain more about this rationale.. This feature will be
removed in a future release.
```

Use [cs_instance_info](https://docs.ansible.com/ansible/latest/modules/cs_instance_info_module.html#cs-instance-info-module) instead. [1] 

---

1. https://docs.ansible.com/ansible/latest/modules/cs_instance_facts_module.html

**Comment by mleutenegger** [comment]
Will look into this and change it.
